### ISSUE TITLE
Formatting of taxon alignment reports should be improved

### ISSUE THREAD

**Issue by zygoballus** [globalbioticinteractions/globinizer#3]
The style of the taxon alignment reports is generated by [generate_styling in check-dataset.sh](https://github.com/globalbioticinteractions/globinizer/blob/52c0dec75ba425b8bac941e32659d7568080e7fc/check-dataset.sh#L620). This CSS was apparently copied from https://benjam.info/panam/styling.css. It utilizes a lot of media queries to implement responsive design, but the responsive design seems to only serve to make sure the result table is always far too big to fit on my screen. I'm guessing this CSS was originally designed for a page that didn't include big tables with URLs in them.

I would recommend adjusting the CSS to significantly reduce the body margins and font-size for each media query tier. The 200px and 20% margins are especially huge. If it were me, I would just set all the body margins to 1em.

**Comment by jhpoelen** [comment]
@zygoballus thanks again for your notes. Do you feel comfortable making the css changes yourself and prepare a pull request?

**Comment by jhpoelen** [comment]
After @zygoballus changes, the tables look a lot more compact than before. See attached before/after .

![after](https://github.com/user-attachments/assets/86620e82-5121-4373-bd2d-14021235bd70)
![before](https://github.com/user-attachments/assets/a7ac9acd-5b89-4054-9150-e29c0f7ba3d8)

**Comment by jhpoelen** [comment]
Thanks for contributing @zygoballus ! Please holler if you have other ideas to improve the use of the review reports.
